name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/csvmon/csvmon:latest
  
  deploy:
    runs-on: self-hosted
  
    steps:
    - name: Deploy to docker on self-hosted runner
      uses: docker/deploy-to-docker-action@v2
      with:
        docker_host: tcp://docker:2375
        docker_context: .
        image_name: ghcr.io/${{ github.repository_owner }}/csvmon/csvmon:latest
